"""
Adaptive RAG domain models.

This module contains data structures used by the adaptive RAG
planning and routing system.

Responsibilities
----------------
- Represent query analysis.
- Represent retrieval strategies.
- Represent retrieval plans.
- Represent routing decisions.
- Represent adaptive RAG configuration.

This module should remain independent of:
- FastAPI
- SQLAlchemy
- PostgreSQL
- Vector stores
- LLM providers
"""

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class RetrievalStrategy(str, Enum):
    """
    Available retrieval strategies.
    """

    VECTOR = "vector"
    KEYWORD = "keyword"
    HYBRID = "hybrid"
    MULTI_QUERY = "multi_query"
    RERANK = "rerank"
    BROAD = "broad"
    DIRECT = "direct"


class QueryComplexity(str, Enum):
    """
    Estimated complexity of a user query.
    """

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class QueryIntent(str, Enum):
    """
    High-level intent detected from the query.
    """

    FACTUAL = "factual"
    EXPLORATORY = "exploratory"
    COMPARATIVE = "comparative"
    ANALYTICAL = "analytical"
    SUMMARIZATION = "summarization"
    MULTI_HOP = "multi_hop"
    UNKNOWN = "unknown"


class RouteDecision(str, Enum):
    """
    Decision made by the adaptive router.
    """

    RETRIEVE = "retrieve"
    RETRIEVE_AND_RERANK = "retrieve_and_rerank"
    MULTI_QUERY = "multi_query"
    HYBRID_RETRIEVAL = "hybrid_retrieval"
    DIRECT_GENERATION = "direct_generation"
    REPLAN = "replan"
    ABORT = "abort"


class QueryAnalysis(BaseModel):
    """
    Analysis of the incoming user query.
    """

    model_config = ConfigDict(extra="allow")

    query: str

    intent: QueryIntent = QueryIntent.UNKNOWN

    complexity: QueryComplexity = QueryComplexity.MEDIUM

    requires_retrieval: bool = True

    requires_multi_hop: bool = False

    requires_reranking: bool = False

    requires_multiple_queries: bool = False

    keywords: list[str] = Field(default_factory=list)

    entities: list[str] = Field(default_factory=list)

    sub_questions: list[str] = Field(default_factory=list)

    confidence: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
    )

    reasoning: str | None = None


class RetrievalPlan(BaseModel):
    """
    Plan generated by the Adaptive RAG planner.
    """

    model_config = ConfigDict(extra="allow")

    strategy: RetrievalStrategy = RetrievalStrategy.HYBRID

    top_k: int = Field(
        default=10,
        ge=1,
        le=100,
    )

    similarity_threshold: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
    )

    max_queries: int = Field(
        default=1,
        ge=1,
        le=10,
    )

    rerank: bool = False

    expand_query: bool = False

    multi_hop: bool = False

    metadata_filters: dict[str, Any] = Field(
        default_factory=dict,
    )

    fallback_strategies: list[RetrievalStrategy] = Field(
        default_factory=list,
    )

    reasoning: str | None = None


class AdaptiveRAGConfig(BaseModel):
    """
    Configuration for Adaptive RAG.
    """

    model_config = ConfigDict(extra="allow")

    default_strategy: RetrievalStrategy = RetrievalStrategy.HYBRID

    default_top_k: int = Field(
        default=10,
        ge=1,
        le=100,
    )

    default_similarity_threshold: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
    )

    enable_query_expansion: bool = True

    enable_multi_query: bool = True

    enable_reranking: bool = True

    enable_multi_hop: bool = True

    max_retries: int = Field(
        default=2,
        ge=0,
        le=10,
    )

    min_retrieval_score: float = Field(
        default=0.3,
        ge=0.0,
        le=1.0,
    )

    max_context_chunks: int = Field(
        default=20,
        ge=1,
        le=100,
    )