/**
 * Frontend types for the Adaptive RAG system.
 *
 * The Adaptive RAG layer is responsible for selecting and executing
 * the most appropriate retrieval strategy for a research query.
 *
 * Supported strategies:
 *
 *   direct
 *   iterative
 *   corrective
 *   multi_query
 *   graph_augmented
 *
 * The graph_augmented strategy does NOT represent a separate Graph RAG
 * API. It is an adaptive retrieval strategy that can combine:
 *
 *   query analysis
 *        ↓
 *   semantic retrieval
 *        ↓
 *   keyword retrieval
 *        ↓
 *   graph expansion
 *        ↓
 *   evidence collection
 *        ↓
 *   reranking
 */
 
/* -------------------------------------------------------------------------- */
/* Shared types                                                               */
/* -------------------------------------------------------------------------- */

/**
 * Arbitrary metadata returned by the backend.
 */
export type AdaptiveRAGMetadata = Record<string, unknown>;

/**
 * UUID values are serialized as strings in JSON responses.
 */
export type AdaptiveRAGId = string;

/**
 * Execution status of an Adaptive RAG request.
 */
export type AdaptiveRAGStatus =
  | "idle"
  | "pending"
  | "analyzing"
  | "planning"
  | "retrieving"
  | "expanding"
  | "reranking"
  | "collecting_evidence"
  | "completed"
  | "failed"
  | "cancelled";

/**
 * Supported Adaptive RAG strategies.
 *
 * These values should remain aligned with the backend strategy
 * implementation.
 */
export type AdaptiveRAGStrategy =
  | "direct"
  | "iterative"
  | "corrective"
  | "multi_query"
  | "graph_augmented";

/**
 * Strategy aliases used by older frontend/backend integrations.
 *
 * Keep this extensible so the frontend can tolerate future strategies.
 */
export type AdaptiveRAGStrategyValue =
  | AdaptiveRAGStrategy
  | string;

/**
 * Retrieval capabilities that Adaptive RAG may activate.
 */
export type AdaptiveRAGRetrievalMethod =
  | "semantic"
  | "keyword"
  | "graph"
  | "hybrid"
  | "unknown"
  | string;

/* -------------------------------------------------------------------------- */
/* Query                                                                       */
/* -------------------------------------------------------------------------- */

/**
 * Query submitted to the Adaptive RAG planner.
 */
export interface AdaptiveRAGQuery {
  /**
   * Original natural-language research query.
   */
  query: string;

  /**
   * Optional paper restriction.
   */
  paper_id?: AdaptiveRAGId | null;

  /**
   * Optional document restriction.
   */
  document_id?: AdaptiveRAGId | null;

  /**
   * Maximum number of final results.
   */
  top_k?: number;

  /**
   * Optional retrieval methods explicitly requested
   * by the frontend.
   *
   * Normally the planner decides this automatically.
   */
  retrieval_methods?: AdaptiveRAGRetrievalMethod[];

  /**
   * Enable graph expansion when supported by the strategy.
   */
  graph_enabled?: boolean;

  /**
   * Maximum graph traversal depth.
   */
  graph_depth?: number;

  /**
   * Maximum number of graph-derived candidates.
   */
  graph_top_k?: number;

  /**
   * Optional filters passed to the retrieval layer.
   */
  filters?: AdaptiveRAGMetadata;

  /**
   * Optional client metadata.
   */
  metadata?: AdaptiveRAGMetadata;
}

/**
 * Query analysis generated by the Adaptive RAG planner.
 */
export interface AdaptiveRAGQueryAnalysis {
  /**
   * Original query.
   */
  original_query: string;

  /**
   * Normalized query.
   */
  normalized_query?: string | null;

  /**
   * Extracted keywords.
   */
  keywords: string[];

  /**
   * Extracted entities.
   */
  entities: string[];

  /**
   * Extracted concepts.
   */
  concepts: string[];

  /**
   * Query complexity score.
   *
   * Convention:
   *
   *   0.0 = very simple
   *   1.0 = highly complex
   */
  complexity?: number | null;

  /**
   * Whether semantic retrieval is required.
   */
  requires_semantic_search?: boolean;

  /**
   * Whether keyword retrieval is required.
   */
  requires_keyword_search?: boolean;

  /**
   * Whether graph retrieval is required.
   */
  requires_graph_search?: boolean;

  /**
   * Whether iterative retrieval is useful.
   */
  requires_iteration?: boolean;

  /**
   * Whether query decomposition is recommended.
   */
  requires_decomposition?: boolean;

  /**
   * Query classification information.
   */
  query_type?: string | null;

  /**
   * Research intent.
   */
  intent?: string | null;

  /**
   * Domain identified by the planner.
   */
  domain?: string | null;

  /**
   * Optional filters inferred from the query.
   */
  filters?: AdaptiveRAGMetadata;

  metadata?: AdaptiveRAGMetadata;
}

/* -------------------------------------------------------------------------- */
/* Strategy selection                                                          */
/* -------------------------------------------------------------------------- */

/**
 * Reason why a particular strategy was selected.
 */
export interface AdaptiveRAGStrategyReason {
  /**
   * Human-readable explanation.
   */
  reason: string;

  /**
   * Score assigned to the strategy.
   */
  score?: number | null;

  /**
   * Signals that contributed to the decision.
   */
  signals?: string[];

  /**
   * Additional planner metadata.
   */
  metadata?: AdaptiveRAGMetadata;
}

/**
 * Strategy selection result.
 */
export interface AdaptiveRAGStrategySelection {
  /**
   * Selected strategy.
   */
  strategy: AdaptiveRAGStrategyValue;

  /**
   * Confidence in the strategy selection.
   *
   * Convention:
   *
   *   0.0 = no confidence
   *   1.0 = very high confidence
   */
  confidence: number;

  /**
   * Explanation for the selected strategy.
   */
  reason?: string | null;

  /**
   * Detailed selection signals.
   */
  reasons?: AdaptiveRAGStrategyReason[];

  /**
   * Alternative strategies considered by the planner.
   */
  alternatives?: AdaptiveRAGStrategyReason[];

  metadata?: AdaptiveRAGMetadata;
}

/* -------------------------------------------------------------------------- */
/* Strategy configuration                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Configuration shared by Adaptive RAG strategies.
 */
export interface AdaptiveRAGConfig {
  /**
   * Default strategy.
   *
   * If omitted, the backend planner automatically selects one.
   */
  strategy?: AdaptiveRAGStrategyValue;

  /**
   * Maximum final results.
   */
  top_k?: number;

  /**
   * Semantic/vector retrieval weight.
   */
  vector_weight?: number;

  /**
   * Keyword retrieval weight.
   */
  keyword_weight?: number;

  /**
   * Enable graph retrieval.
   */
  graph_enabled?: boolean;

  /**
   * Maximum graph traversal depth.
   */
  graph_depth?: number;

  /**
   * Maximum graph-derived candidates.
   */
  graph_top_k?: number;

  /**
   * Maximum number of retrieval iterations.
   */
  max_iterations?: number;

  /**
   * Maximum number of generated queries for multi-query retrieval.
   */
  max_queries?: number;

  /**
   * Enable corrective retrieval.
   */
  corrective_enabled?: boolean;

  /**
   * Minimum confidence required before accepting results.
   */
  confidence_threshold?: number;

  /**
   * Optional backend-specific configuration.
   */
  metadata?: AdaptiveRAGMetadata;
}

/* -------------------------------------------------------------------------- */
/* Retrieval step                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Individual step executed by an Adaptive RAG strategy.
 */
export interface AdaptiveRAGStep {
  /**
   * Unique step identifier.
   */
  id: AdaptiveRAGId;

  /**
   * Sequential execution order.
   */
  order: number;

  /**
   * Human-readable step name.
   */
  name: string;

  /**
   * Step type.
   */
  type:
    | "query_analysis"
    | "query_classification"
    | "query_rewrite"
    | "query_decomposition"
    | "semantic_retrieval"
    | "keyword_retrieval"
    | "graph_retrieval"
    | "graph_expansion"
    | "multi_query"
    | "corrective_retrieval"
    | "iterative_retrieval"
    | "fusion"
    | "reranking"
    | "evidence_collection"
    | "provenance"
    | "validation"
    | "completion"
    | string;

  /**
   * Execution status.
   */
  status: AdaptiveRAGStatus;

  /**
   * Optional start timestamp.
   */
  started_at?: string | null;

  /**
   * Optional completion timestamp.
   */
  completed_at?: string | null;

  /**
   * Number of results produced by this step.
   */
  result_count?: number | null;

  /**
   * Optional step message.
   */
  message?: string | null;

  /**
   * Optional error.
   */
  error?: string | null;

  metadata?: AdaptiveRAGMetadata;
}

/* -------------------------------------------------------------------------- */
/* Query variants                                                              */
/* -------------------------------------------------------------------------- */

/**
 * Query generated by the multi-query or corrective strategy.
 */
export interface AdaptiveRAGQueryVariant {
  /**
   * Generated query.
   */
  query: string;

  /**
   * Position in the generated query set.
   */
  index: number;

  /**
   * Reason for generating this query.
   */
  reason?: string | null;

  /**
   * Retrieval methods intended for this query.
   */
  retrieval_methods?: AdaptiveRAGRetrievalMethod[];

  /**
   * Optional score assigned by the query generator.
   */
  score?: number | null;

  metadata?: AdaptiveRAGMetadata;
}

/**
 * Collection of query variants.
 */
export interface AdaptiveRAGQueryExpansion {
  /**
   * Original query.
   */
  original_query: string;

  /**
   * Generated query variants.
   */
  queries: AdaptiveRAGQueryVariant[];

  /**
   * Number of generated variants.
   */
  count: number;

  metadata?: AdaptiveRAGMetadata;
}

/* -------------------------------------------------------------------------- */
/* Graph augmentation                                                          */
/* -------------------------------------------------------------------------- */

/**
 * A node discovered during graph augmentation.
 *
 * This deliberately remains lightweight because the canonical
 * graph domain types live in `src/types/graph.ts`.
 */
export interface AdaptiveRAGGraphNode {
  id: AdaptiveRAGId;

  type: string;

  label?: string | null;

  score?: number | null;

  metadata?: AdaptiveRAGMetadata;
}

/**
 * Relationship discovered during graph augmentation.
 */
export interface AdaptiveRAGGraphEdge {
  id: AdaptiveRAGId;

  type: string;

  source_node_id: AdaptiveRAGId;

  target_node_id: AdaptiveRAGId;

  score?: number | null;

  metadata?: AdaptiveRAGMetadata;
}

/**
 * Graph path used to augment retrieval.
 */
export interface AdaptiveRAGGraphPath {
  nodes: AdaptiveRAGGraphNode[];

  edges?: AdaptiveRAGGraphEdge[];

  score?: number | null;

  depth?: number;

  metadata?: AdaptiveRAGMetadata;
}

/**
 * Graph augmentation result.
 *
 * This represents the graph contribution to an Adaptive RAG
 * execution, not a separate retrieval API.
 */
export interface AdaptiveRAGGraphAugmentation {
  /**
   * Whether graph augmentation was used.
   */
  enabled: boolean;

  /**
   * Whether the planner determined graph traversal was necessary.
   */
  required?: boolean;

  /**
   * Nodes discovered from the query.
   */
  nodes: AdaptiveRAGGraphNode[];

  /**
   * Edges discovered during traversal.
   */
  edges: AdaptiveRAGGraphEdge[];

  /**
   * Traversal paths.
   */
  paths: AdaptiveRAGGraphPath[];

  /**
   * Maximum traversal depth used.
   */
  depth?: number | null;

  /**
   * Number of graph-derived candidates.
   */
  result_count?: number;

  metadata?: AdaptiveRAGMetadata;
}

/* -------------------------------------------------------------------------- */
/* Retrieval execution                                                         */
/* -------------------------------------------------------------------------- */

/**
 * Summary of retrieval performed during one Adaptive RAG execution.
 */
export interface AdaptiveRAGRetrievalSummary {
  /**
   * Retrieval capabilities actually used.
   */
  methods: AdaptiveRAGRetrievalMethod[];

  /**
   * Semantic results generated.
   */
  semantic_count?: number;

  /**
   * Keyword results generated.
   */
  keyword_count?: number;

  /**
   * Graph results generated.
   */
  graph_count?: number;

  /**
   * Number of results after fusion.
   */
  fused_count?: number;

  /**
   * Number of results after reranking.
   */
  reranked_count?: number;

  /**
   * Number of evidence items collected.
   */
  evidence_count?: number;

  metadata?: AdaptiveRAGMetadata;
}

/* -------------------------------------------------------------------------- */
/* Quality / confidence                                                        */
/* -------------------------------------------------------------------------- */

/**
 * Quality assessment generated after retrieval.
 */
export interface AdaptiveRAGQualityAssessment {
  /**
   * Overall quality score.
   *
   * Convention:
   *
   *   0.0 = poor
   *   1.0 = excellent
   */
  score: number;

  /**
   * Whether the retrieved evidence is considered sufficient.
   */
  sufficient: boolean;

  /**
   * Evidence coverage score.
   */
  coverage?: number | null;

  /**
   * Relevance score.
   */
  relevance?: number | null;

  /**
   * Diversity score.
   */
  diversity?: number | null;

  /**
   * Graph coverage when graph augmentation was used.
   */
  graph_coverage?: number | null;

  /**
   * Human-readable quality explanation.
   */
  reason?: string | null;

  /**
   * Signals used by the evaluator.
   */
  signals?: string[];

  metadata?: AdaptiveRAGMetadata;
}

/* -------------------------------------------------------------------------- */
/* Corrective retrieval                                                        */
/* -------------------------------------------------------------------------- */

/**
 * Corrective action taken when initial retrieval quality
 * is insufficient.
 */
export interface AdaptiveRAGCorrection {
  /**
   * Whether correction was triggered.
   */
  triggered: boolean;

  /**
   * Reason correction was triggered.
   */
  reason?: string | null;

  /**
   * Corrective action.
   */
  action?:
    | "rewrite_query"
    | "expand_query"
    | "increase_top_k"
    | "enable_keyword"
    | "enable_semantic"
    | "enable_graph"
    | "increase_graph_depth"
    | "retry"
    | "stop"
    | string;

  /**
   * Query used after correction.
   */
  corrected_query?: string | null;

  /**
   * Quality score before correction.
   */
  previous_quality?: number | null;

  /**
   * Quality score after correction.
   */
  resulting_quality?: number | null;

  metadata?: AdaptiveRAGMetadata;
}

/* -------------------------------------------------------------------------- */
/* Iterative retrieval                                                         */
/* -------------------------------------------------------------------------- */

/**
 * One iteration of an iterative Adaptive RAG execution.
 */
export interface AdaptiveRAGIteration {
  /**
   * Iteration number starting at 1.
   */
  iteration: number;

  /**
   * Query used for this iteration.
   */
  query: string;

  /**
   * Retrieval methods used.
   */
  retrieval_methods: AdaptiveRAGRetrievalMethod[];

  /**
   * Number of candidates produced.
   */
  result_count?: number;

  /**
   * Quality assessment after this iteration.
   */
  quality?: AdaptiveRAGQualityAssessment | null;

  /**
   * Whether another iteration is required.
   */
  continue_iteration?: boolean;

  metadata?: AdaptiveRAGMetadata;
}

/* -------------------------------------------------------------------------- */
/* Final execution result                                                      */
/* -------------------------------------------------------------------------- */

/**
 * Canonical Adaptive RAG response.
 *
 * This is the top-level object consumed by the frontend.
 *
 * Conceptually:
 *
 * AdaptiveRAGResponse
 * │
 * ├── query
 * ├── strategy
 * ├── strategy_selection
 * ├── query_analysis
 * ├── query_expansion
 * ├── graph_augmentation
 * ├── retrieval
 * ├── iterations
 * ├── correction
 * ├── quality
 * └── results
 */
export interface AdaptiveRAGResponse {
  /**
   * Unique execution identifier.
   */
  execution_id: AdaptiveRAGId;

  /**
   * Original query.
   */
  query: string;

  /**
   * Strategy selected for the execution.
   */
  strategy: AdaptiveRAGStrategyValue;

  /**
   * Strategy selection details.
   */
  strategy_selection?: AdaptiveRAGStrategySelection | null;

  /**
   * Overall execution status.
   */
  status: AdaptiveRAGStatus;

  /**
   * Query analysis.
   */
  query_analysis?: AdaptiveRAGQueryAnalysis | null;

  /**
   * Query expansion generated by multi-query/corrective strategies.
   */
  query_expansion?: AdaptiveRAGQueryExpansion | null;

  /**
   * Graph augmentation information.
   *
   * Present when graph_augmented is selected or when the
   * planner activates graph retrieval for another strategy.
   */
  graph_augmentation?: AdaptiveRAGGraphAugmentation | null;

  /**
   * Retrieval execution summary.
   */
  retrieval?: AdaptiveRAGRetrievalSummary | null;

  /**
   * Iteration history.
   */
  iterations?: AdaptiveRAGIteration[];

  /**
   * Corrective retrieval information.
   */
  correction?: AdaptiveRAGCorrection | null;

  /**
   * Final quality assessment.
   */
  quality?: AdaptiveRAGQualityAssessment | null;

  /**
   * Retrieval results.
   *
   * The canonical result shape is defined in `retrieval.ts`.
   *
   * Kept as `unknown[]` here to avoid duplicating the retrieval
   * contract and creating circular type dependencies.
   *
   * The API layer should map these to `RetrievalResult[]`.
   */
  results: unknown[];

  /**
   * Number of final results.
   */
  total: number;

  /**
   * Execution steps.
   */
  steps?: AdaptiveRAGStep[];

  /**
   * Total execution time in milliseconds.
   */
  execution_time_ms?: number | null;

  /**
   * Backend diagnostics.
   */
  metadata: AdaptiveRAGMetadata;

  /**
   * Error information when execution fails.
   */
  error?: string | null;

  /**
   * Creation timestamp.
   */
  created_at?: string | null;

  /**
   * Completion timestamp.
   */
  completed_at?: string | null;
}

/* -------------------------------------------------------------------------- */
/* Execution status                                                            */
/* -------------------------------------------------------------------------- */

/**
 * Lightweight status returned by a polling/status endpoint.
 */
export interface AdaptiveRAGExecutionStatus {
  execution_id: AdaptiveRAGId;

  status: AdaptiveRAGStatus;

  strategy?: AdaptiveRAGStrategyValue | null;

  current_step?: string | null;

  current_stage?: string | null;

  progress?: number | null;

  message?: string | null;

  started_at?: string | null;

  completed_at?: string | null;

  execution_time_ms?: number | null;

  error?: string | null;

  metadata?: AdaptiveRAGMetadata;
}

/**
 * List response for Adaptive RAG executions.
 */
export interface AdaptiveRAGExecutionListResponse {
  items: AdaptiveRAGExecutionStatus[];

  total: number;

  page: number;

  page_size: number;

  pages: number;
}

/* -------------------------------------------------------------------------- */
/* Frontend execution state                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Frontend-only state used while an Adaptive RAG request is running.
 */
export interface AdaptiveRAGPipelineState {
  status: AdaptiveRAGStatus;

  stage?: string | null;

  progress?: number | null;

  strategy?: AdaptiveRAGStrategyValue | null;

  message?: string | null;

  error?: string | null;

  /**
   * Steps displayed in the research workspace.
   */
  steps: AdaptiveRAGStep[];
}

/* -------------------------------------------------------------------------- */
/* Strategy metadata                                                           */
/* -------------------------------------------------------------------------- */

/**
 * Human-readable information about an Adaptive RAG strategy.
 *
 * Useful for strategy selectors, dashboards, and debugging panels.
 */
export interface AdaptiveRAGStrategyInfo {
  strategy: AdaptiveRAGStrategyValue;

  name: string;

  description: string;

  /**
   * Retrieval capabilities normally associated with this strategy.
   */
  retrieval_methods: AdaptiveRAGRetrievalMethod[];

  /**
   * Whether the strategy supports iterative execution.
   */
  supports_iteration: boolean;

  /**
   * Whether the strategy supports query expansion.
   */
  supports_multi_query: boolean;

  /**
   * Whether the strategy supports corrective retrieval.
   */
  supports_correction: boolean;

  /**
   * Whether the strategy supports graph augmentation.
   */
  supports_graph: boolean;

  metadata?: AdaptiveRAGMetadata;
}

/**
 * Default metadata for the currently supported strategies.
 */
export const ADAPTIVE_RAG_STRATEGIES: AdaptiveRAGStrategyInfo[] = [
  {
    strategy: "direct",
    name: "Direct",
    description:
      "Execute a straightforward retrieval pipeline for the research query.",
    retrieval_methods: ["semantic", "keyword"],
    supports_iteration: false,
    supports_multi_query: false,
    supports_correction: false,
    supports_graph: false,
  },

  {
    strategy: "iterative",
    name: "Iterative",
    description:
      "Retrieve, evaluate evidence quality, and continue retrieval when additional evidence is required.",
    retrieval_methods: ["semantic", "keyword"],
    supports_iteration: true,
    supports_multi_query: false,
    supports_correction: false,
    supports_graph: false,
  },

  {
    strategy: "corrective",
    name: "Corrective",
    description:
      "Evaluate initial retrieval quality and perform corrective retrieval when evidence is insufficient.",
    retrieval_methods: ["semantic", "keyword"],
    supports_iteration: false,
    supports_multi_query: false,
    supports_correction: true,
    supports_graph: false,
  },

  {
    strategy: "multi_query",
    name: "Multi Query",
    description:
      "Generate multiple query variants to improve retrieval coverage.",
    retrieval_methods: ["semantic", "keyword"],
    supports_iteration: false,
    supports_multi_query: true,
    supports_correction: false,
    supports_graph: false,
  },

  {
    strategy: "graph_augmented",
    name: "Graph Augmented",
    description:
      "Augment semantic and keyword retrieval with knowledge-graph traversal and graph-derived evidence.",
    retrieval_methods: ["semantic", "keyword", "graph"],
    supports_iteration: true,
    supports_multi_query: true,
    supports_correction: true,
    supports_graph: true,
  },
];

/* -------------------------------------------------------------------------- */
/* Utility helpers                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Determine whether a strategy supports graph augmentation.
 */
export function isGraphAugmentedStrategy(
  strategy: AdaptiveRAGStrategyValue,
): boolean {
  return strategy === "graph_augmented";
}

/**
 * Determine whether a strategy can perform iterative retrieval.
 */
export function supportsAdaptiveRAGIteration(
  strategy: AdaptiveRAGStrategyValue,
): boolean {
  return (
    strategy === "iterative" ||
    strategy === "graph_augmented"
  );
}

/**
 * Determine whether a strategy supports query expansion.
 */
export function supportsAdaptiveRAGQueryExpansion(
  strategy: AdaptiveRAGStrategyValue,
): boolean {
  return (
    strategy === "multi_query" ||
    strategy === "corrective" ||
    strategy === "graph_augmented"
  );
}

/**
 * Determine whether a strategy supports corrective retrieval.
 */
export function supportsAdaptiveRAGCorrection(
  strategy: AdaptiveRAGStrategyValue,
): boolean {
  return (
    strategy === "corrective" ||
    strategy === "graph_augmented"
  );
}

/**
 * Determine whether the current execution is still running.
 */
export function isAdaptiveRAGRunning(
  status: AdaptiveRAGStatus,
): boolean {
  return (
    status === "pending" ||
    status === "analyzing" ||
    status === "planning" ||
    status === "retrieving" ||
    status === "expanding" ||
    status === "reranking" ||
    status === "collecting_evidence"
  );
}

/**
 * Determine whether the execution has reached a terminal state.
 */
export function isAdaptiveRAGTerminal(
  status: AdaptiveRAGStatus,
): boolean {
  return (
    status === "completed" ||
    status === "failed" ||
    status === "cancelled"
  );
}