from enum import Enum
from typing import List, Dict, Optional
from pydantic import BaseModel, Field


# -------------------------------------------------
# Query Intent Types
# -------------------------------------------------

class QueryIntent(str, Enum):
    """
    Represents what type of information
    the user is looking for.
    """

    FACTUAL = "factual"

    RESEARCH = "research"

    CODING = "coding"

    COMPARISON = "comparison"

    SUMMARY = "summary"

    TROUBLESHOOTING = "troubleshooting"

    EXPLANATION = "explanation"



# -------------------------------------------------
# Query Analysis Result
# -------------------------------------------------

class QueryAnalysis(BaseModel):
    """
    Output of query understanding stage.

    Example:

    User:
    "Explain LoRA"

    Output:

    {
        intent: research,
        rewritten_query:
        "Low Rank Adaptation paper..."
    }
    """

    original_query: str


    rewritten_query: Optional[str] = None


    intent: Optional[QueryIntent] = None


    sub_queries: List[str] = Field(
        default_factory=list
    )


    selected_sources: List[str] = Field(
        default_factory=list
    )


    metadata: Dict = Field(
        default_factory=dict
    )



# -------------------------------------------------
# Retrieval Source
# -------------------------------------------------

class RetrievalSource(str, Enum):
    """
    Available knowledge sources.
    """

    VECTOR_DB = "vector_db"

    BM25 = "bm25"

    ARXIV = "arxiv"

    GITHUB = "github"

    DOCUMENTATION = "documentation"

    WEB = "web"



# -------------------------------------------------
# Retrieval Task
# -------------------------------------------------

class RetrievalTask(BaseModel):
    """
    A single retrieval operation.

    Example:

    Search arxiv for:
    "LoRA paper architecture"
    """

    query: str


    source: RetrievalSource


    top_k: int = 5


    filters: Dict = Field(
        default_factory=dict
    )



# -------------------------------------------------
# Retrieval Plan
# -------------------------------------------------

class RetrievalPlan(BaseModel):
    """
    Generated by Retrieval Planner.

    Converts:

    User Query

    into:

    Multiple retrieval tasks
    """

    original_query: str


    intent: QueryIntent


    tasks: List[RetrievalTask] = Field(
        default_factory=list
    )


    execution_strategy: str = "parallel"



# -------------------------------------------------
# Retrieved Document
# -------------------------------------------------

class RetrievedDocument(BaseModel):
    """
    Standard document format
    returned by every retriever.
    """

    id: str


    content: str


    source: str


    score: float


    metadata: Dict = Field(
        default_factory=dict
    )



# -------------------------------------------------
# Retrieval Result
# -------------------------------------------------

class RetrievalResult(BaseModel):
    """
    Final output after retrieval.
    """

    query: str


    documents: List[RetrievedDocument] = Field(
        default_factory=list
    )


    total_documents: int = 0


    metadata: Dict = Field(
        default_factory=dict
    )