"""add research observatory models

Revision ID: 40006d1571e6
Revises: 1937a0622735
Create Date: 2026-08-24 19:42:13.247893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40006d1571e6'
down_revision: Union[str, Sequence[str], None] = '1937a0622735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_slug'), 'research_projects', ['slug'], unique=True)
    op.create_index(op.f('ix_research_projects_status'), 'research_projects', ['status'], unique=False)
    op.create_index(op.f('ix_research_projects_user_id'), 'research_projects', ['user_id'], unique=False)
    op.create_table('research_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_executions_project_id'), 'research_executions', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_executions_status'), 'research_executions', ['status'], unique=False)
    op.create_table('research_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('result_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['research_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_results_execution_id'), 'research_results', ['execution_id'], unique=False)
    op.create_index(op.f('ix_research_results_project_id'), 'research_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_results_result_type'), 'research_results', ['result_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_results_result_type'), table_name='research_results')
    op.drop_index(op.f('ix_research_results_project_id'), table_name='research_results')
    op.drop_index(op.f('ix_research_results_execution_id'), table_name='research_results')
    op.drop_table('research_results')
    op.drop_index(op.f('ix_research_executions_status'), table_name='research_executions')
    op.drop_index(op.f('ix_research_executions_project_id'), table_name='research_executions')
    op.drop_table('research_executions')
    op.drop_index(op.f('ix_research_projects_user_id'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_status'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_slug'), table_name='research_projects')
    op.drop_table('research_projects')
    # ### end Alembic commands ###
