"""initial users and papers schema

Revision ID: 6aafa36160cf
Revises: 
Create Date: 2026-08-15 22:00:11.233138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aafa36160cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orcid', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('given_name', sa.String(length=255), nullable=True),
    sa.Column('family_name', sa.String(length=255), nullable=True),
    sa.Column('affiliation', sa.Text(), nullable=True),
    sa.Column('author_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_full_name'), 'authors', ['full_name'], unique=False)
    op.create_index(op.f('ix_authors_orcid'), 'authors', ['orcid'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=False)
    op.create_table('methods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_methods_name'), 'methods', ['name'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=True),
    sa.Column('venue_type', sa.String(length=100), nullable=True),
    sa.Column('issn', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_issn'), 'venues', ['issn'], unique=False)
    op.create_index(op.f('ix_venues_name'), 'venues', ['name'], unique=False)
    op.create_index(op.f('ix_venues_normalized_name'), 'venues', ['normalized_name'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doi', sa.String(length=512), nullable=True),
    sa.Column('arxiv_id', sa.String(length=255), nullable=True),
    sa.Column('pmid', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_paper_id', sa.String(length=512), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('reference_count', sa.Integer(), nullable=False),
    sa.Column('landing_page_url', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('source_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi', name='uq_papers_doi'),
    sa.UniqueConstraint('provider', 'provider_paper_id', name='uq_papers_provider_id')
    )
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=False)
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_index(op.f('ix_papers_pmid'), 'papers', ['pmid'], unique=False)
    op.create_index(op.f('ix_papers_provider'), 'papers', ['provider'], unique=False)
    op.create_index(op.f('ix_papers_publication_date'), 'papers', ['publication_date'], unique=False)
    op.create_index(op.f('ix_papers_title'), 'papers', ['title'], unique=False)
    op.create_index(op.f('ix_papers_venue_id'), 'papers', ['venue_id'], unique=False)
    op.create_index(op.f('ix_papers_year'), 'papers', ['year'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('citing_paper_id', sa.Integer(), nullable=False),
    sa.Column('cited_paper_id', sa.Integer(), nullable=False),
    sa.Column('citation_context', sa.String(length=2000), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cited_paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['citing_paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('citing_paper_id', 'cited_paper_id', name='uq_citation_pair')
    )
    op.create_index(op.f('ix_citations_cited_paper_id'), 'citations', ['cited_paper_id'], unique=False)
    op.create_index(op.f('ix_citations_citing_paper_id'), 'citations', ['citing_paper_id'], unique=False)
    op.create_table('paper_authors',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'author_id')
    )
    op.create_table('paper_datasets',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'dataset_id')
    )
    op.create_table('paper_methods',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['method_id'], ['methods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'method_id')
    )
    op.create_table('paper_topics',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paper_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_topics')
    op.drop_table('paper_methods')
    op.drop_table('paper_datasets')
    op.drop_table('paper_authors')
    op.drop_index(op.f('ix_citations_citing_paper_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_cited_paper_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_papers_year'), table_name='papers')
    op.drop_index(op.f('ix_papers_venue_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_title'), table_name='papers')
    op.drop_index(op.f('ix_papers_publication_date'), table_name='papers')
    op.drop_index(op.f('ix_papers_provider'), table_name='papers')
    op.drop_index(op.f('ix_papers_pmid'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_venues_normalized_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_name'), table_name='venues')
    op.drop_index(op.f('ix_venues_issn'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_methods_name'), table_name='methods')
    op.drop_table('methods')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_authors_orcid'), table_name='authors')
    op.drop_index(op.f('ix_authors_full_name'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
